# Generated by Django 5.1.3 on 2024-11-27 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechaP',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
