# Generated by Django 5.1.3 on 2024-11-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fechap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fechaP',
        ),
    ]
