# Generated by Django 5.1.3 on 2024-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_fechap'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechasP',
            field=models.DateField(default='2024-11-12'),
            preserve_default=False,
        ),
    ]
